### ISSUE TITLE
Sightingdb location

### ISSUE THREAD

**Issue by ch4r13** [DevoInc/sightingdb#11]
Hello, for me It's quite hard. 
Can anyone explain, where to git clone sighting dir? 
Should it be in `/home/user` or just in ` / ` .

Another question is, how to run sighting-daemon... Iam quite newbie in Linux.

Thanks for reply.

**Comment by stricaud** [comment]
You can clone it in /home/user or /opt if you prefer. 

To run the sighting-daemon, have a look at the generated binary in targets/release or debug.

**Comment by ch4r13** [comment]
So, It's trying to unwrap() 
```
user@ubu-srv-101:~/sightingdb$ ./target/debug/sighting-daemon
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/daemon/main.rs:93:61
stack backtrace:
```
When I look at src/daemon.main.rs:93:61

```

user@ubu-srv-101:~/sightingdb$ cat ./src/daemon/main.rs | head -n 100 | tail -n 10
    let mut sharedstate = Arc::new(Mutex::new(SharedState::new()));

    let config = Ini::load_from_file("sighting-daemon.ini").unwrap();

    let daemon_config = config.section(Some("daemon")).unwrap();
    match daemon_config.get("daemonize").unwrap().as_ref() {
        "true" => { Daemonize::new().pid_file("/var/run/sightingdb.pid").start().unwrap(); },
        "false" => println!("This daemon is not daemonized. To run in background, set 'daemon = true' in sigthing-daemon.ini"),
        _ => println!("Unknown daemon setting. Starting in foreground."),
    }

```

Any Idea, What is incorrect?
